# 服务端口
server:
  port: 8080

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 666666
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# MyBatis-Plus配置
mybatis-plus:
  # 逻辑删除配置
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  # 控制台打印SQL
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Knife4j配置
knife4j:
  enable: true